version: "2.4"

volumes:
    cmdbuild-db:
    cmdbuild-tomcat:

services:
    cmdbuild_db:
        image: postgis/postgis:17-3.5-alpine
        container_name: cmdbuild_db
        volumes:
            - cmdbuild-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always

    cmdbuild_app:
        image: itmicus/cmdbuild:app-3.4.4
        container_name: cmdbuild_app
        links:
           - cmdbuild_db
        depends_on:
           - cmdbuild_db
        ports:
            - 8090:8080
        restart: always  
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=cmdbuild_db
            - POSTGRES_DB=cmdbuild_3
            - CMDBUILD_DUMP=demo
            - JAVA_OPTS=-Xmx4000m -Xms2000m
        mem_limit: 4000m
        mem_reservation: 2000m
